name: publish-to-gh

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-south-1"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Deploy to S3
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: dist
          bucket: viralspiral.net
          dist-id: ELBFBHCZBXW7L
          invalidation: / *
